name: AntiSpawner
version: 1.0.0
main: ru.antispawner.AntiSpawnerPlugin
api-version: 1.21
description: Запрет на ломание спавнеров с шансом для привилегированных игроков
author: YourName
commands:
  asreload:
    description: Перезагрузить конфигурацию плагина
    usage: /asreload
    permission: antispawner.reload
permissions:
  antispawner.reload:
    description: Право на перезагрузку плагина
    default: op
  antispawner.break:
    description: Право на попытку сломать спавнер (с шансом)
    default: false
